title: Isaac Sanchez
logo: /assets/img/round_flecki.png
description: 'Master’s graduate in Nanoelectronic Systems with hands-on experience in RTL design and digital verification at IP and SoC level. Skilled in SystemVerilog, UVM, assertions, and functional coverage, with a solid background in scripting and EDA tools. Experienced in creating and improving verification environments, collaborating across design and verification teams to ensure robust, high-quality designs.'

# Other Config
show_downloads: false
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
